jobs:
- template: ./job.yml
  parameters:
    jobName: macOS
    vmImage: macOS-latest
    os: osx

# For faster CI turnaround, linux builds are still on Travis
# - template: ./linux.yml
#   parameters:
#     jobName: Linux
#     vmImage: ubuntu-latest
#     os: linux

- template: ./job.yml
  parameters:
    jobName: Windows
    vmImage: windows-latest
    os: windows
    stackRoot: "$(System.DefaultWorkingDirectory)\\s"
    stackWork: ".w"
    stackProjectPath: "$(Build.SourcesDirectory)\\Color\\"
    preBuildSteps:
    - powershell: |
        xcopy "$env:STACK_ROOT\\bin" "$env:LOCALAPPDATA\\Programs\\stack" /f /s /r /k /i /h /y /b
      displayName: Restore binaries
      condition: eq(variables.STACK_ROOT_RESTORED, 'true')
      continueOnError: true
    postBuildSteps:
    - powershell: |
        xcopy "$env:LOCALAPPDATA\\Programs\\stack" "$env:STACK_ROOT\\bin" /f /s /r /k /i /h /y /b
      displayName: Save binaries
      continueOnError: true
    doctestAllowFailure: true
    # GHC keeps printing a warning causing doctests to fail.
    # ghc.exe: addLibrarySearchPath: C:\Users\V .... \mingw64\bin (Win32 error 2): The system cannot find the file specified.
